name: Create Index HTML File

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: "Create a folder called output"
        run: |
          mkdir output
          cp resume-stylesheet.css output/resume-stylesheet.css
          cp resume.md output/${{ github.actor }}-resume.md
      # downloading the binaries directly, because they are newer and work better, than the ones that come with Ubuntu latest.
      - name: "Install pandoc"
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.3/pandoc-3.3-1-amd64.deb
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.jammy_amd64.deb
          sudo apt install ./pandoc-3.3-1-amd64.deb
          sudo apt install ./wkhtmltox_0.12.6.1-3.jammy_amd64.deb

      - name: "Convert MD to HTML"
        run: |
          pandoc resume.md -f markdown -t html -c resume-stylesheet.css -s -o output/${{github.actor}}-resume.html
          cp output/${{github.actor}}-resume.html $REPO_REL_DIR/index.html
          cp output/${{github.actor}}-resume.html output/index.html

      - name: "Convert HTML to PDF"
        run: "wkhtmltopdf --enable-local-file-access output/${{github.actor}}-resume.html output/${{github.actor}}-resume.pdf"
      - uses: actions/upload-artifact@master
        with:
          name: ${{ github.actor }}'s Resume
          path: $REPO_REL_DIR/index.html
  