name: Create Index HTML File

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: "Install pandoc"
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.3/pandoc-3.3-1-amd64.deb
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-3/wkhtmltox_0.12.6.1-3.jammy_amd64.deb
          sudo apt install ./pandoc-3.3-1-amd64.deb
          sudo apt install ./wkhtmltox_0.12.6.1-3.jammy_amd64.deb

      - name: "Convert MD to HTML"
        run: |
          pandoc resume.md -f markdown -t html -c resume-stylesheet.css -s -o index.html

      - name: "Convert HTML to PDF"
        run: "wkhtmltopdf --enable-local-file-access index.html ${{github.actor}}-resume.pdf"
      - uses: actions/upload-artifact@master
        with:
          name: ${{ github.actor }} Resume
          path: resume.pdf
